spring.application.name=SpiringBootDataJpa
###############################
######## DataSource Config ###############
########################################
#spring.datasource.url=jdbc:postgresql://localhost:5432/demo_app_db
#spring.datasource.password=3884
#spring.datasource.username=postgres
#spring.datasource.driver-class-name=org.postgresql.Driver

#############################
###### JPA Config #######
###############################
#spring.jpa.show-sql=true
#spring.jpa.hibernate.ddl-auto=update
#spring.jpa.properties.hibernate.format_sql=true

spring.data.rest.base-path=/api
spring.data.rest.page-param-name=sahifa // pageni nomini ozgartirish
spring.data.rest.max-page-size=2

