spring.application.name=SpiringBootDataJpa
spring.datasource.url=jdbc:postgresql://localhost:5432/demo_app_db
spring.datasource.username=postgres
spring.datasource.password=3884
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.datasource.driver-class-name=org.postgresql.Driver

