<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Mail</title>
</head>
<body style="color: cornflowerblue; margin: 0; padding: 0">
<h1 style="text-align: center; color: green; ">Hello for ${username}</h1>
<h3>You have successfully registered!!!!</h3>
<h3>In Order to Active your Account please click link below!!!</h3>
<a href="http://localhost:8080/activate?token=${token}">Activate</a>
</body>
</html>